[licenses]
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
]

[licenses.private]
ignore = true

[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-wildcard-paths = true

[sources]
unknown-registry = "deny"
unknown-git = "deny"
